# Generated by Django 3.2.3 on 2021-06-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(choices=[('about bg', 'la page about'), ('gallery bg', 'la page gallerie'), ('contact bg', 'la page contact')], max_length=100, null=True, verbose_name='Pour qelle page ?'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.FileField(upload_to='img', verbose_name='image de fond'),
        ),
    ]
