# Generated by Django 3.2.3 on 2021-06-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210604_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(choices=[('about_bg', 'la page about'), ('gallery_bg', 'la page gallerie'), ('contact_bg', 'la page contact')], max_length=100, null=True, verbose_name='Pour qelle page ?'),
        ),
    ]
