# Generated by Django 3.2.3 on 2021-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img')),
                ('label', models.CharField(max_length=200, verbose_name='titre')),
                ('price', models.FloatField(verbose_name='prix')),
                ('number', models.IntegerField(verbose_name='numéro')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name="date d'ajout")),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'gallerie',
            },
        ),
    ]
